name: Testes RESTCOUNTRIES testes pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests-Modelo-Blackbox:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome]
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Atualize para a versão mais recente que suporta Node.js  20
      - name: Install modules
        run: npm install
      - name: Run end-to-end black box tests 🧪
        uses: cypress-io/github-action@v6 # Atualize para a versão mais recente que suporta Node.js  20
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          command: npm run cypress:run
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/*.mp4
      - name: Upload Mochawesome reports
        uses: actions/upload-artifact@v4
        with:
            name: mochawesome-reports
            path: cypress/reports/*.html